{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-core",
    "version": "4307936-ps17-cmp07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp07.jar",
          "url": "remote-core-4307936-ps17-cmp07.jar",
          "size": 1588039,
          "sha512": "355b41f67b6e4917e3cd0983bcc4257ad7af9b887c99f77d12816cd1ee1192bc44a99b80d87c35e73b2197598ab87ecd5a7584a6a528c19cd6c0f6b2ce45ebec",
          "sha256": "fc2dfc645ade4dcdd20616812f344919ac249f6e45b32860d1408fa688642a7b",
          "sha1": "21c38d20ac7e61e680cb9e0f09f985ad1d42c8c7",
          "md5": "1cf907aa67e775d2a2adf93eaff00eeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp07.jar",
          "url": "remote-core-4307936-ps17-cmp07.jar",
          "size": 1588039,
          "sha512": "355b41f67b6e4917e3cd0983bcc4257ad7af9b887c99f77d12816cd1ee1192bc44a99b80d87c35e73b2197598ab87ecd5a7584a6a528c19cd6c0f6b2ce45ebec",
          "sha256": "fc2dfc645ade4dcdd20616812f344919ac249f6e45b32860d1408fa688642a7b",
          "sha1": "21c38d20ac7e61e680cb9e0f09f985ad1d42c8c7",
          "md5": "1cf907aa67e775d2a2adf93eaff00eeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp07-sources.jar",
          "url": "remote-core-4307936-ps17-cmp07-sources.jar",
          "size": 873277,
          "sha512": "b245304b09ed3e73e727d278f22eeca8b8b3e1fd25f8fc492ec8069dbca4d0eb77560fb62c6b8043b469b741a30ca98b5e64caa179ab933ce48e55faaee01d67",
          "sha256": "64f9d4dba3bee568be7c95f7702b173adfb21c5086af574ef5235ecea6c9f4b6",
          "sha1": "c52c089bd9a2435c1a3602fc705cc88e3ad57d71",
          "md5": "b50ef7351ecd8458b0ec49eb47eb0573"
        }
      ]
    }
  ]
}
