{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-write-core",
    "version": "4307936-ps17-cmp08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-metadata-4307936-ps17-cmp08.jar",
          "url": "remote-write-core-4307936-ps17-cmp08.jar",
          "size": 24770,
          "sha512": "5053df602718105d868caeaee9770921d6050e9bd50f418ba71c724d35bd273794d1de00056c5503ef2c4bbfc89bbdef676eff86566836df56577788d6f1fbb7",
          "sha256": "09ad0c3785e53086e2ef95041bce6c41b6c405d29c81e18f60cacbb97e71e199",
          "sha1": "1f2717a9c4c2e2bbb388d2cf53b33fe73464df8e",
          "md5": "eb1cb3f30107503beadb5a0f26a6c921"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "remote-write-core-kotlin-4307936-ps17-cmp08-sources.jar",
          "url": "remote-write-core-4307936-ps17-cmp08-sources.jar",
          "size": 25171,
          "sha512": "fb9d99c8319ef156624b8eb83180d277ffe37a34259fb22328179bd87eb1a6efe38fa8d89f6ffd02829c6af19598f3737118b144aa5ea1ae18e440d053dd7712",
          "sha256": "d54159f275113450e2a8e1a508a0dae4fc7375eb413f3139ca613452e712897c",
          "sha1": "0107d0b7b29bffaf5ce123f92a20c361f2ef20cc",
          "md5": "044b51007b6cc5fbcba6bf4b0d218c62"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-write-core-jvm/4307936-ps17-cmp08/remote-write-core-jvm-4307936-ps17-cmp08.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-jvm",
        "version": "4307936-ps17-cmp08"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-write-core-jvm/4307936-ps17-cmp08/remote-write-core-jvm-4307936-ps17-cmp08.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-jvm",
        "version": "4307936-ps17-cmp08"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-write-core-jvm/4307936-ps17-cmp08/remote-write-core-jvm-4307936-ps17-cmp08.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-jvm",
        "version": "4307936-ps17-cmp08"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-write-core-wasm-js/4307936-ps17-cmp08/remote-write-core-wasm-js-4307936-ps17-cmp08.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-wasm-js",
        "version": "4307936-ps17-cmp08"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-write-core-wasm-js/4307936-ps17-cmp08/remote-write-core-wasm-js-4307936-ps17-cmp08.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-wasm-js",
        "version": "4307936-ps17-cmp08"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-write-core-wasm-js/4307936-ps17-cmp08/remote-write-core-wasm-js-4307936-ps17-cmp08.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-wasm-js",
        "version": "4307936-ps17-cmp08"
      }
    }
  ]
}
