{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-material3/4307936-ps17-cmp09/remote-material3-4307936-ps17-cmp09.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-material3",
    "version": "4307936-ps17-cmp09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.1-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-material3-wasm-js-4307936-ps17-cmp09.klib",
          "url": "remote-material3-wasm-js-4307936-ps17-cmp09.klib",
          "size": 540089,
          "sha512": "55dd57f4f0c4d24c380a8cf1b500b807e87478c1e3b9d86f1445a5a5a3e2a5733a6fdfa47f21d550b16850c817399186afabb941f5513fe40f557bc86ca17473",
          "sha256": "5fecd242d6cddda3ba7707ffa3c7a8455a1e8ff95258171b751f0f48d04ec841",
          "sha1": "467867b807153813da42c0cc97275072ae3864e5",
          "md5": "376ba34938472a7034fb1c23f8198433"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.1-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "remote-material3-wasm-js-4307936-ps17-cmp09.klib",
          "url": "remote-material3-wasm-js-4307936-ps17-cmp09.klib",
          "size": 540089,
          "sha512": "55dd57f4f0c4d24c380a8cf1b500b807e87478c1e3b9d86f1445a5a5a3e2a5733a6fdfa47f21d550b16850c817399186afabb941f5513fe40f557bc86ca17473",
          "sha256": "5fecd242d6cddda3ba7707ffa3c7a8455a1e8ff95258171b751f0f48d04ec841",
          "sha1": "467867b807153813da42c0cc97275072ae3864e5",
          "md5": "376ba34938472a7034fb1c23f8198433"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "remote-material3-wasm-js-4307936-ps17-cmp09-sources.jar",
          "url": "remote-material3-wasm-js-4307936-ps17-cmp09-sources.jar",
          "size": 115994,
          "sha512": "8221a3394ef5bceea0da23141f6debd8e56d1c46018ce8ca11225efe33f422adfccf8757692a0d09e5d1f72741965f2ab47e6d7329fb1ea390bca2fc5d0aaaed",
          "sha256": "92c8281d3561bf452198d21e258b24b5093e7d913e72fe572b94a92eb5d0f93e",
          "sha1": "548f1e1765bd2ad4ff7a0096f015641ad1c74689",
          "md5": "97213cfd7970ddeb9a396387d564251b"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.1-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "remote-material3-4307936-ps17-cmp09.kotlin_resources.zip",
          "url": "remote-material3-wasm-js-4307936-ps17-cmp09-kotlin_resources.kotlin_resources.zip",
          "size": 370,
          "sha512": "4833cc8a8114461f950381e243b81dfdd21679216ec02243e0e68c6904c189149b2c0a94e1a191a33827d116941905134377880f36c1adf74602c49f311e9d17",
          "sha256": "0c3d6d788e4409502b1e4e411c06c1e509d01a4622eec3bcaa5ff0616b2325b3",
          "sha1": "3c009e585c75c079b63450335278ddb473fd32d4",
          "md5": "507a01e316f29b4ff7c3c4c8dcb1d3b1"
        }
      ]
    }
  ]
}
