{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-creation-compose/4307936-ps17-cmp09/remote-creation-compose-4307936-ps17-cmp09.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-creation-compose",
    "version": "4307936-ps17-cmp09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.remote",
          "module": "remote-creation",
          "version": {
            "requires": "1.0.0-alpha21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose.aar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp09.aar",
          "size": 1661158,
          "sha512": "dd78a50deded5506324f1e159acb446722d3c942c9bf9a3354380b39eb3ec120f6a2038b7d4ca19f9dd455c208e25f24768d7faa8fdb3d819a88b9e6d970878a",
          "sha256": "59a1c248ecb6a6b3ba1d9ebc2c32ef92d51f17c9b96b23679ca58040892ab1fc",
          "sha1": "9101fb5d0ccfa58685d8023cb17b7cbcb32c2f8f",
          "md5": "aa8aa9fe3ed531ddc268ea22841f7f0e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.remote",
          "module": "remote-creation",
          "version": {
            "requires": "1.0.0-alpha21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-path",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose.aar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp09.aar",
          "size": 1661158,
          "sha512": "dd78a50deded5506324f1e159acb446722d3c942c9bf9a3354380b39eb3ec120f6a2038b7d4ca19f9dd455c208e25f24768d7faa8fdb3d819a88b9e6d970878a",
          "sha256": "59a1c248ecb6a6b3ba1d9ebc2c32ef92d51f17c9b96b23679ca58040892ab1fc",
          "sha1": "9101fb5d0ccfa58685d8023cb17b7cbcb32c2f8f",
          "md5": "aa8aa9fe3ed531ddc268ea22841f7f0e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-creation-compose-android-4307936-ps17-cmp09-sources.jar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp09-sources.jar",
          "size": 400308,
          "sha512": "ac550d4ad6482e86462a24ff839d83b08eabe5677c4a7d64f0ea8d3e0d08fe2ad9610daccc5fb4da7bf6e336d3d5fed3991e52e99aecec4659e2f9670af0019d",
          "sha256": "706e6f7e85e5496a8cd6fdf0821bfb832739cf9968bacf1c12ae13e107acc2c1",
          "sha1": "14ca7581132ab73eef48cf12621cf7b6652087a2",
          "md5": "0a4d5955fda5755c410cad0338e93268"
        }
      ]
    }
  ]
}
