{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-core",
    "version": "4307936-ps17-cmp09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp09.jar",
          "url": "remote-core-4307936-ps17-cmp09.jar",
          "size": 1588575,
          "sha512": "035720516c496e80ab90812c5e304669ba91e148194f0abc80441434a3ae8a0ab796107f01cd27a84dcd751460a177586ad707eae70d8858b167ba79767b90a2",
          "sha256": "6119f6ecc0fa3ae4a8d011d59399d18405739633a2c755d0c31049caa9eeff29",
          "sha1": "736dacab96fbde3c99281bccbd1033bc97e70040",
          "md5": "991748a8ef8632c7affb24781c242828"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp09.jar",
          "url": "remote-core-4307936-ps17-cmp09.jar",
          "size": 1588575,
          "sha512": "035720516c496e80ab90812c5e304669ba91e148194f0abc80441434a3ae8a0ab796107f01cd27a84dcd751460a177586ad707eae70d8858b167ba79767b90a2",
          "sha256": "6119f6ecc0fa3ae4a8d011d59399d18405739633a2c755d0c31049caa9eeff29",
          "sha1": "736dacab96fbde3c99281bccbd1033bc97e70040",
          "md5": "991748a8ef8632c7affb24781c242828"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp09-sources.jar",
          "url": "remote-core-4307936-ps17-cmp09-sources.jar",
          "size": 873667,
          "sha512": "ddc4a78cd902b77cf733b9245fc5e93f78d0931c72646ab8c63267969dfdd26b928f2fb581c0ab9faaa5e18777c193ed2b79062647f1824766aefb36997578bb",
          "sha256": "c52f80ebbffa213cb0b0b7b09c4f2b8c6327e3a4212176dab4933840544cc6e1",
          "sha1": "e04e30fb539102a24bc2652a5b53afc9ca256a8f",
          "md5": "b7bf1877409a738b425f4cf02e6b021f"
        }
      ]
    }
  ]
}
