{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-material3/4307936-ps17-cmp09/remote-material3-4307936-ps17-cmp09.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-material3",
    "version": "4307936-ps17-cmp09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.1-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-material3-jvm-4307936-ps17-cmp09.jar",
          "url": "remote-material3-jvm-4307936-ps17-cmp09.jar",
          "size": 403504,
          "sha512": "0f4d34aed41c979c659064d1ffc0d40e26a02a2d25352fc9bf46ae37ffec8218379fd0042b8444968118d13ef99535aebef7ec6c8dd9042bd313899ee56d1333",
          "sha256": "54092563b63516d756341e5bd7c7ede60a04d3052dacb28d66b06c810ad3f237",
          "sha1": "7a990fb1cf50006c3dce9464d07abf831d07a58c",
          "md5": "7220558bb295d0e71f8fe0e5921fc12f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.1-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp09"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "remote-material3-jvm-4307936-ps17-cmp09.jar",
          "url": "remote-material3-jvm-4307936-ps17-cmp09.jar",
          "size": 403504,
          "sha512": "0f4d34aed41c979c659064d1ffc0d40e26a02a2d25352fc9bf46ae37ffec8218379fd0042b8444968118d13ef99535aebef7ec6c8dd9042bd313899ee56d1333",
          "sha256": "54092563b63516d756341e5bd7c7ede60a04d3052dacb28d66b06c810ad3f237",
          "sha1": "7a990fb1cf50006c3dce9464d07abf831d07a58c",
          "md5": "7220558bb295d0e71f8fe0e5921fc12f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "remote-material3-jvm-4307936-ps17-cmp09-sources.jar",
          "url": "remote-material3-jvm-4307936-ps17-cmp09-sources.jar",
          "size": 116287,
          "sha512": "07d00f419859f291de3dd272685d75397314ef5639729aa4b85912ef7ec2f5de16f7b847f431659e11f66d72168211128d3f6f9b8399bfb062f0790603a340d3",
          "sha256": "87105bb5f9150501127c1451586d7de95b0c2455312d4c1b6fd6dafda1ad4a00",
          "sha1": "b880fe1dffeac3c6e13ea2bbc4cdc05394087f4b",
          "md5": "8958b91385240579a79e0d1c52461688"
        }
      ]
    }
  ]
}
