{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-write-core/4307936-ps17-cmp09/remote-write-core-4307936-ps17-cmp09.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-write-core",
    "version": "4307936-ps17-cmp09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp09.klib",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp09.klib",
          "size": 202553,
          "sha512": "c3f8fb566e7ddf2191f45274aed0f625ea7a90d08ab65a796011ced039125ef527d78fc64fa1b4854ac84660d9b36565e5f6fa64224b384581007a3cdf45baa0",
          "sha256": "0187d57e7b8e2fa84882c45d150e0e138336a13da33f3b01c6b4c94fa9d4bb01",
          "sha1": "5eec5389bdea1a778f7086cedfefc814ff1f5ff3",
          "md5": "4e0239020f35deb89eefe459cfaadaca"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp09.klib",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp09.klib",
          "size": 202553,
          "sha512": "c3f8fb566e7ddf2191f45274aed0f625ea7a90d08ab65a796011ced039125ef527d78fc64fa1b4854ac84660d9b36565e5f6fa64224b384581007a3cdf45baa0",
          "sha256": "0187d57e7b8e2fa84882c45d150e0e138336a13da33f3b01c6b4c94fa9d4bb01",
          "sha1": "5eec5389bdea1a778f7086cedfefc814ff1f5ff3",
          "md5": "4e0239020f35deb89eefe459cfaadaca"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp09-sources.jar",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp09-sources.jar",
          "size": 25171,
          "sha512": "fb9d99c8319ef156624b8eb83180d277ffe37a34259fb22328179bd87eb1a6efe38fa8d89f6ffd02829c6af19598f3737118b144aa5ea1ae18e440d053dd7712",
          "sha256": "d54159f275113450e2a8e1a508a0dae4fc7375eb413f3139ca613452e712897c",
          "sha1": "0107d0b7b29bffaf5ce123f92a20c361f2ef20cc",
          "md5": "044b51007b6cc5fbcba6bf4b0d218c62"
        }
      ]
    }
  ]
}
