{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-foundation/4307936-ps17-cmp08/remote-foundation-4307936-ps17-cmp08.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-foundation",
    "version": "4307936-ps17-cmp08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-foundation-wasm-js-4307936-ps17-cmp08.klib",
          "url": "remote-foundation-wasm-js-4307936-ps17-cmp08.klib",
          "size": 22821,
          "sha512": "9cf027499b4b5bb6ee33ca79778a272e704bdb8dc13ecdba5dddc53f56ccc454ba6bbc1292af025bc173b7cfbfe9c96578b29e65f4c98b4be3270c96e8fa097c",
          "sha256": "3cf029da2c7867cd45ad6c5f951bd0c6cc70d7fcbc9125b622cf382893387049",
          "sha1": "3e457a64354650e3593fdb6f9426b524a044276f",
          "md5": "5a870cd180b9802207adb3a5356bc297"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-foundation-wasm-js-4307936-ps17-cmp08.klib",
          "url": "remote-foundation-wasm-js-4307936-ps17-cmp08.klib",
          "size": 22821,
          "sha512": "9cf027499b4b5bb6ee33ca79778a272e704bdb8dc13ecdba5dddc53f56ccc454ba6bbc1292af025bc173b7cfbfe9c96578b29e65f4c98b4be3270c96e8fa097c",
          "sha256": "3cf029da2c7867cd45ad6c5f951bd0c6cc70d7fcbc9125b622cf382893387049",
          "sha1": "3e457a64354650e3593fdb6f9426b524a044276f",
          "md5": "5a870cd180b9802207adb3a5356bc297"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "remote-foundation-wasm-js-4307936-ps17-cmp08-sources.jar",
          "url": "remote-foundation-wasm-js-4307936-ps17-cmp08-sources.jar",
          "size": 6589,
          "sha512": "d4d5b12f82aad1eced7a4eb674ab5186c9ce3193b676d0f5ad87afa21c2019e6220d175a5bd1b3e2ba0acac7a3e8a5727a76632a624d39a6cb220f58c3abf0e5",
          "sha256": "1d5c41415ff2cd3c8f6193de82ccd24a75998df3457c7a1a5846ebfd1852968b",
          "sha1": "99e982ba5cca9ab311e5c1d445a175f4375431a9",
          "md5": "d5f0900e5aac32288372fe193f338bde"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-foundation-4307936-ps17-cmp08.kotlin_resources.zip",
          "url": "remote-foundation-wasm-js-4307936-ps17-cmp08-kotlin_resources.kotlin_resources.zip",
          "size": 372,
          "sha512": "0fd533ee7203d043a1b91f2376032341dd0084e3eb49b190985b13256743c4ccb8c0706ece1e824182181bc446db50de87e7c018abfaa528fd09955bd04df972",
          "sha256": "75f4d2ec90ce3f8a1c47c22c9cb0dad6500ea0a02c2b903734ce1ee352a4eb8c",
          "sha1": "4a7f340d492e606456c6a80f0d289d750a261b1e",
          "md5": "d90173bfba94b075bfd2d2d2a776cf91"
        }
      ]
    }
  ]
}
