{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-write-core/4307936-ps17-cmp07/remote-write-core-4307936-ps17-cmp07.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-write-core",
    "version": "4307936-ps17-cmp07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-jvm-4307936-ps17-cmp07.jar",
          "url": "remote-write-core-jvm-4307936-ps17-cmp07.jar",
          "size": 169672,
          "sha512": "d36d4009c60179cf261768c6bc14afee7f0b67974c27e6f11cf3d59450d5857062db05bad3e3607b7ad60df10fab320f39806b2ab4020339b07fb24e1c6b50b0",
          "sha256": "704f936620f2ea69c3cdad15996be5df758709a1f5a461c619ed08dd9a47ef3a",
          "sha1": "c5d1014627aae63aa31108c99b9dfc59df3d74c2",
          "md5": "c7d8af6275eb539da4a1867ed20395be"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-jvm-4307936-ps17-cmp07.jar",
          "url": "remote-write-core-jvm-4307936-ps17-cmp07.jar",
          "size": 169672,
          "sha512": "d36d4009c60179cf261768c6bc14afee7f0b67974c27e6f11cf3d59450d5857062db05bad3e3607b7ad60df10fab320f39806b2ab4020339b07fb24e1c6b50b0",
          "sha256": "704f936620f2ea69c3cdad15996be5df758709a1f5a461c619ed08dd9a47ef3a",
          "sha1": "c5d1014627aae63aa31108c99b9dfc59df3d74c2",
          "md5": "c7d8af6275eb539da4a1867ed20395be"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "remote-write-core-jvm-4307936-ps17-cmp07-sources.jar",
          "url": "remote-write-core-jvm-4307936-ps17-cmp07-sources.jar",
          "size": 25171,
          "sha512": "fb9d99c8319ef156624b8eb83180d277ffe37a34259fb22328179bd87eb1a6efe38fa8d89f6ffd02829c6af19598f3737118b144aa5ea1ae18e440d053dd7712",
          "sha256": "d54159f275113450e2a8e1a508a0dae4fc7375eb413f3139ca613452e712897c",
          "sha1": "0107d0b7b29bffaf5ce123f92a20c361f2ef20cc",
          "md5": "044b51007b6cc5fbcba6bf4b0d218c62"
        }
      ]
    }
  ]
}
